sonar:
  stage: test
  image: maven:3-jdk-11-slim
  script: "mvn --batch-mode clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=tibhannover -Dsonar.login=${SONAR_LOGIN} -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Pcoverage"
  cache:
    paths:
    - .m2/repository
    