variables:
  MAVEN_CLI_OPTS: "--batch-mode -s ci_settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
    
include:
  - local: '.gitlab-ci-sonar.yml'

build:
  image: maven:latest
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  image: maven:latest
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

.deploy_job:
  stage: deploy
  before_script:
    - "PROJECTVERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"
    - echo VERSION=${PROJECTVERSION} > build.info
    - echo BUILDNUMBER=${CI_JOB_ID} >> build.info
    - echo COMMIT_SHA=${CI_COMMIT_SHORT_SHA} >> build.info
    - date +'TIMESTAMP=%Y%m%d%H%M%S' >> build.info
    - cat build.info
    - mv build.info src/main/resources

deploy branch:
  image: maven:latest
  extends: .deploy_job
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
     - target/*.war
  only:
    - branches
    
deploy release:
  image: maven:latest
  extends: .deploy_job
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - tags

.git_writer:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$GITLAB_SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "gitlab-ci@oersi.de"
    - git config --global user.name "gitlab-ci"

version update:
  extends: .git_writer
  stage: .post
  script:
    - git checkout $CI_COMMIT_BRANCH
  only:
    - adjust-project-version-after-change
