image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
    
include:
  - local: '.gitlab-ci-sonar.yml'

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    
deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
     - target/*.war
    