image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode -s ci_settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
    
include:
  - local: '.gitlab-ci-sonar.yml'

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

.deploy_job:
  stage: deploy
  before_script:
    - "PROJECTVERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"
    - echo VERSION=${PROJECTVERSION} > build.info
    - echo BUILDNUMBER=${CI_JOB_ID} >> build.info
    - echo COMMIT_SHA=${CI_COMMIT_SHORT_SHA} >> build.info
    - date +'TIMESTAMP=%Y%m%d%H%M%S' >> build.info
    - cat build.info
    - mv build.info src/main/resources

deploy branch:
  extends: .deploy_job
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
     - target/*.war
  only:
    - branches
    
deploy release:
  extends: .deploy_job
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - tags
    
