openapi: 3.0.1
info:
  title: OER Search Index REST API
  description: This is the Swagger Documentation of the OER Search Index REST API.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: /
tags:
  - name: config-controller
    description: EndPoint for Backend configuration
  - name: label-controller
    description: Endpoints for access to labels
  - name: metadata-controller
    description: Every EndPoint for Metadata Controller
  - name: oembed-Controller
    description: oEmbed provider endpoint
  - name: search-Controller
    description: Every EndPoint for Search Controller
  - name: vocab-Controller
    description: vocab endpoint
paths:
  /api/label/{language}:
    $ref: "label.yaml#/~1api~1label~1{language}"
  /api/deprecated/label/{language}:
    $ref: "label.yaml#/~1api~1deprecated~1label~1{language}"

  /api/contact:
    $ref: "contact.yaml#/~1api~1contact"

  /api/metadata:
    $ref: "metadata.yaml#/~1api~1metadata"
  /api/metadata/bulk:
    $ref: "metadata.yaml#/~1api~1metadata~1bulk"
  /api/metadata/source:
    $ref: "metadata.yaml#/~1api~1metadata~1source"
  /api/metadata/source/{id}:
    $ref: "metadata.yaml#/~1api~1metadata~1source~1{id}"
  /api/metadata/{id}:
    $ref: "metadata.yaml#/~1api~1metadata~1{id}"

  /api/metadata-config:
    $ref: "config.yaml#/~1api~1metadata-config"

  /api/oembed-json:
    $ref: "oembed.yaml#/~1api~1oembed-json"
  /api/oembed-xml:
    $ref: "oembed.yaml#/~1api~1oembed-xml"

  /api/search/**:
    $ref: "search.yaml#/~1api~1search~1**"

  /api/vocab/bulk:
    $ref: "vocab.yaml#/~1api~1vocab~1bulk"

components:
  schemas:
    LocalizedString:
      title: Localized String
      type: object
      example:
        de: 'Mathematik'
        en: 'Mathematics'
      additionalProperties:
        type: string
      description: "A language-tagged string using JSON-LD \"language maps\", see\
        \ https://www.w3.org/TR/json-ld/#language-maps. Valid keys are ISO-639-1 language\
        \ codes."
