swagger: "2.0"
info:
  description: "This is the Swagger Documentation of the OER Search Index REST API."
  version: "1.0.0"
  title: "OER Search Index REST API"
  termsOfService: " "
  contact:
    email: "edmond.kacaj@tib.eu"
  license:
    name: "MIT License"
    url: "https://opensource.org/licenses/MIT"
basePath: "/api"
tags:
  - name: "search-Controller"
    description: "Every EndPoint for Search Controller "
  - name: "metadata-controller"
    description: "Every EndPoint for Metadata Controller"

paths:
  /metadata:
    post:
      tags:
        - "metadata-controller"
      summary: "Create or Update "
      description: "With this end-point we can create or update  Metadata "
      operationId: "createOrUpdate"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Metadata Object needs to be added   "
          required: true
          schema:
            $ref: "#/definitions/Metadata"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Metadata"
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    delete:
      tags:
        - "metadata-controller"
      summary: "Delete all metadata"
      description: "Delete all existing metadata"
      operationId: "deleteAll"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /metadata/{id}:
    put:
      tags:
        - "metadata-controller"
      summary: "Update an existing Metadata"
      description: "With this end-point we can  update an existing  Metadata "
      operationId: "update"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: id
          in: path
          description: "Id to update Metadata"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "Metadata Object needs to be added "
          required: true
          schema:
            $ref: "#/definitions/Metadata"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Metadata"
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    delete:
      tags:
        - "metadata-controller"
      summary: "Delete metadata by ID"
      description: "For valid response try integer IDs with positive integer value.         Negative or non-integer values will generate API errors"
      operationId: "delete"
      produces:
        - "application/json"
      parameters:
        - name: id
          in: path
          description: "ID of the metadata that needs to be deleted"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Metadata"
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    get:
      tags:
        - "metadata-controller"
      summary: "Find Metadata by Id"
      description: "With this end-point we can  get by Id  an existing  Metadata"
      operationId: "findById"
      produces:
        - "application/json"
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/Metadata"
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /search/**:
    post:
      tags:
        - "search-controller"
      summary: "Find Metadata by Id"
      description: |
        **Request Body Search**
        <br/><br/>
        **Specifies search criteria as request body parameters.**
        <br/><br/>
        <em>The search request can be executed with a search DSL, which includes the [Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html), within its body.g.</em>
        <br/><br/>
        **Example**
        <br/><br/>
          **Request**
         ```
           GET /<index>/_search
            {
              "query": {<parameters>}
            }
         ```
        <br/><br/>
        Form more info about Request Body Search you can find here [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#search-request-body).

      operationId: "processElasticsearchPostRequest"
      produces:
        - "application/json"
      parameters:
        - name: body
          in: body
          description: |
            **Elastic Search**
            <br/>
            **Schema Example**
            <br/>
             Example Show all
             <br/><br/>
              ```
               {
                 "query": {
                   "match_all": {}
                 }
              }
              ```

          required: false
          schema:
            type: string
            example: '{"query": {"match_all": {}}}'

      responses:
        '200':
          description: |
            **Elastic Search Json Object**
            <br/>
            **This is a dynamic JSON come from elastic search**
            <br/>
            **Don't have a default Schema. Is a String**
          schema:
            type: string
            example: "Dynamic JSON String come from ElasticSearch "
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /search/**/?{params}:
    get:
      tags:
        - "search-controller"
      summary: "Find Metadata by params "
      description:  |
        **URI Search**
        <br/><br/>
        **Specifies search criteria as query parameters in the request URI.**
        <br/><br/>
        <em>You can use query parameters to define your search criteria directly in the request URI, rather than in the request body. Request URI searches do not support the full Elasticsearch Query DSL, but are handy for testing.</em>
        <br/><br/>
         **Example:**
         <br/><br/>
          **Request:**
         ```
         GET /<index>/_search?q=<parameter>
         ```
        <br/><br/>
        Form more info about URI Search you can find here [URI Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html).

      operationId: "processElasticsearchGetRequest"
      produces:
        - "application/json"
      parameters:
        - name: "params"
          in: "path"
          description: "e.g size=1000&pretty=true"
          required: true
          type: "string"
          default: "size=1000&pretty=true"
          collectionFormat: "csv"
      responses:
        '200':
          description: |
            **Elastic Search Json Object**
            <br/>
            **This is a dynamic JSON come from elastic search**
            <br/>
             **Don't have a default Schema. Is a String**
          schema:
            type: string
            example: "Dynamic JSON String come from ElasticSearch "
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found



definitions:
  Metadata:
    properties:
      "@context":
        title: "JSON-LD Context"
        type: "array"
        minItems: 2
        description: "The JSON-LD context for the structured resource descriptions"
        items:
          - type: "string"
            format: "uri"
            example: "https://w3id.org/kim/lrmi-profile/draft/context.jsonld"
          - type: "object"
            properties:
              "@language":
                type: "string"
                example: "de"
                required:
                  - "@language"
        example:
          - "https://w3id.org/kim/lrmi-profile/draft/context.jsonld"
          - "@language": "de"
      id:
        title: "URL"
        type: "string"
        format: "uri"
        description: "The URI of the resource"
        example: "https://axel-klinger.gitlab.io/gitlab-for-documents/index.html"
      name:
        title: "Title"
        type: "string"
        description: "Title of the educational resource"
        example: "GitLab für Texte"
      creator:
        title: "Creator"
        type: "array"
        description: "Creator"
        items:
          type: "object"
          properties:
            type:
              title: "Type"
              type: "string"
              description: "Type"
              example: "Person"
              enum:
                - "Person"
                - "Organization"
            id:
              type: "string"
              format: "uri"
              description: "identifier of the person/organization like orcid, gnd or ror"
            name:
              title: "Name"
              type: "string"
              description: "The creator's name"
              example: "Max Mustermann"
          required:
            - "name"
            - "type"
      description:
        title: "Description"
        type: "string"
        description: "A short description of the resource"
        example: "an example description"
      about:
        title: "Subject"
        type: "array"
        description: "Classification of the educational resource"
        items:
          type: "object"
          properties:
            id:
              type: "string"
              example: "https://w3id.org/kim/hochschulfaechersystematik/n105"
            prefLabel:
              title: "The preferred label of the concept"
              description: "A localized string for prefLabel of the classification"
              $ref: "#/definitions/LocalizedString"
          required:
            - "id"
      license:
        title: "License"
        type: "string"
        format: "uri"
        description: "URL of the License."
        example: "https://creativecommons.org/licenses/by/4.0/deed.de"
      image:
        title: "Image"
        type: "string"
        description: "A link to an image of the resource"
        format: "uri"
        example: "https://www.oernds.de/edu-sharing/preview?nodeId=84400a83-9d1a-4738-a19f-00fc332df247&storeProtocol=workspace&storeId=SpacesStore&dontcache=1589890988103"
      dateCreated:
        title: "Creation Date"
        type: "string"
        format: "date"
        description: "date on which the educational resource was created. format: YYYY-MM-DD"
        example: "2020-02-22"
      datePublished:
        title: "Publication Date"
        type: "string"
        format: "date"
        description: "date on which the educational resource was published. format: YYYY-MM-DD"
        example: "2020-02-22"
      inLanguage:
        title: "Language"
        type: "string"
        description: "Language code ISO 639-1"
        example: "en"
        enum:
          - "aa"
          - "ab"
          - "ae"
          - "af"
          - "ak"
          - "am"
          - "an"
          - "ar"
          - "as"
          - "av"
          - "ay"
          - "az"
          - "ba"
          - "be"
          - "bg"
          - "bh"
          - "bi"
          - "bm"
          - "bn"
          - "bo"
          - "br"
          - "bs"
          - "ca"
          - "ce"
          - "ch"
          - "co"
          - "cr"
          - "cs"
          - "cu"
          - "cv"
          - "cy"
          - "da"
          - "de"
          - "dv"
          - "dz"
          - "ee"
          - "el"
          - "en"
          - "eo"
          - "es"
          - "et"
          - "eu"
          - "fa"
          - "ff"
          - "fi"
          - "fj"
          - "fo"
          - "fr"
          - "fy"
          - "ga"
          - "gd"
          - "gl"
          - "gn"
          - "gu"
          - "gv"
          - "ha"
          - "hi"
          - "ho"
          - "hr"
          - "ht"
          - "hu"
          - "hy"
          - "hz"
          - "ia"
          - "ie"
          - "ig"
          - "ii"
          - "ik"
          - "io"
          - "is"
          - "it"
          - "iu"
          - "ja"
          - "jv"
          - "ka"
          - "kg"
          - "ki"
          - "kj"
          - "kk"
          - "kl"
          - "km"
          - "kn"
          - "ko"
          - "kr"
          - "ks"
          - "ku"
          - "kv"
          - "kw"
          - "ky"
          - "la"
          - "lb"
          - "lg"
          - "li"
          - "ln"
          - "lo"
          - "lt"
          - "lu"
          - "lv"
          - "mg"
          - "mh"
          - "mi"
          - "mk"
          - "ml"
          - "mn"
          - "mo"
          - "mr"
          - "ms"
          - "mt"
          - "my"
          - "na"
          - "nb"
          - "nd"
          - "ne"
          - "ng"
          - "nl"
          - "nn"
          - "no"
          - "nr"
          - "nv"
          - "nvi"
          - "ny"
          - "oc"
          - "oj"
          - "om"
          - "or"
          - "os"
          - "pa"
          - "pi"
          - "pl"
          - "ps"
          - "pt"
          - "qu"
          - "rm"
          - "rn"
          - "ro"
          - "ru"
          - "rw"
          - "sa"
          - "sc"
          - "sd"
          - "se"
          - "sg"
          - "si"
          - "sk"
          - "sl"
          - "sm"
          - "smi"
          - "sn"
          - "so"
          - "sq"
          - "sr"
          - "ss"
          - "st"
          - "su"
          - "sv"
          - "sw"
          - "ta"
          - "te"
          - "tg"
          - "th"
          - "ti"
          - "tk"
          - "tl"
          - "tn"
          - "to"
          - "tr"
          - "ts"
          - "tt"
          - "tw"
          - "ty"
          - "ug"
          - "uk"
          - "ur"
          - "uz"
          - "ve"
          - "vi"
          - "vo"
          - "wa"
          - "wo"
          - "xh"
          - "yo"
          - "za"
          - "zh"
          - "zu"
      learningResourceType:
        title: "Learning Resource Type"
        type: "object"
        description: "Learning Resource Type"
        properties:
          id:
            type: "string"
            example: "https://w3id.org/kim/hcrt/course"
          prefLabel:
            title: "The preferred label of the concept"
            description: "A localized string for prefLabel of the learning resource type"
            $ref: "#/definitions/LocalizedString"
# error with such examples - see https://github.com/OpenAPITools/openapi-generator/issues/3140
#        example:
#          id: "https://w3id.org/kim/hcrt/course"
#          prefLabel:
#            de: Kurs
#            en: Course
      audience:
        title: "Audience"
        type: "object"
        description: "Audience / interactivity level"
        properties:
          id:
            type: "string"
            example: "http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/student"
          prefLabel:
            title: "The preferred label of the concept"
            description: "A localized string for prefLabel of the audience"
            $ref: "#/definitions/LocalizedString"
      mainEntityOfPage:
        title: "metadata description"
        description: "This object contains metametadata, i.e. information about the description of the OER."
        type: "array"
        items:
          type: "object"
          properties:
            id:
              type: "string"
              format: "uri"
              description: "The URI of the metadata"
              example: "https://www.oernds.de/edu-sharing/components/render/84400a83-9d1a-4738-a19f-00fc332df247"
            type:
              type: "string"
              description: "Type of the metadata description"
              example: "WebPage"
            dateCreated:
              title: "Creation date of the metadata"
              type: "string"
              format: "date"
              description: "Creation date of the metadata. format: YYYY-MM-DD"
              example: "2020-03-21"
            dateModified:
              title: "Date of last modification of the metadata"
              type: "string"
              format: "date"
              description: "Date of last modification of the metadata. format: YYYY-MM-DD"
              example: "2020-03-22"
            provider:
              title: "Provider"
              description: "Site or service that is source of the metadata"
              type: "object"
              properties:
                id:
                  type: "string"
                  format: "uri"
                  description: "The URI for the metadata provider"
                  example: "https://oerworldmap.org/resource/urn:uuid:4062c64d-b0ac-4941-95c2-8116f137326d"
                type:
                  type: "string"
                  description: "Type of the metadata provider"
                  example: "Service"
                name:
                  type: "string"
                  description: "The name of the metadata provider"
                  example: "ZOERR"
          required:
            - "id"
      sourceOrganization:
        title: "Source Organization"
        description: "The Organization on whose behalf the creator was working."
        type: "array"
        items:
          type: "object"
          properties:
            id:
              type: "string"
              format: "uri"
              description: "The URI for the source organization"
              example: "http://www.wikidata.org/entity/Q54166"
            type:
              type: "string"
              description: "Type of the source organization"
              example: "Organization"
            name:
              type: "string"
              description: "The name of the source organization"
              example: "Technische Hochschule Köln"
      keywords:
        title: "Keywords"
        description: "Keywords or tags used to describe this content"
        type: "array"
        example:
          - Multimedia
          - GitLab
        items:
          type: "string"
    required:
      - "id"
      - "name"

  LocalizedString:
    title: "Localized String"
    description: "A language-tagged string using JSON-LD \"language maps\", see https://www.w3.org/TR/json-ld/#language-maps. Valid keys are ISO-639-1 language codes."
    type: "object"
# see https://swagger.io/docs/specification/data-models/dictionaries/
# validation of iso-639-1 language keys in business logic
    additionalProperties:
      type: string

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"